# Generated by Django 5.0.6 on 2024-05-25 23:05
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="room_amenities",
        ),
        migrations.RemoveField(
            model_name="roomtype",
            name="room_amenities",
        ),
    ]
