# Generated by Django 5.0.6 on 2024-05-19 09:46
import uuid

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("literals", "0003_hostel_semester_year"),
        ("room", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="hostel",
            field=models.ForeignKey(
                default="fabf76c7-63b3-465e-a017-291a47f930d7",
                on_delete=django.db.models.deletion.PROTECT,
                to="literals.university",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="room",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="room/%Y-%m-%d"),
        ),
        migrations.CreateModel(
            name="RoomPricing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                (
                    "length_of_stay",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="room.room"
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="literals.semester",
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="literals.year"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
