# Generated by Django 5.0.6 on 2024-05-19 11:53
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("literals", "0003_hostel_semester_year"),
        ("room", "0002_room_hostel_room_image_roompricing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="hostel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="literals.hostel"
            ),
        ),
    ]
