# Generated by Django 5.0.6 on 2024-05-25 23:39
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("literals", "0001_initial"),
        ("room", "0002_remove_room_room_amenities_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="room_amenities",
            field=models.ManyToManyField(blank=True, to="room.roomamenity"),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="hostel",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="literals.hostel",
            ),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="room_amenities",
            field=models.ManyToManyField(blank=True, to="room.roomamenity"),
        ),
    ]
