# Generated by Django 5.0.6 on 2024-05-26 01:48
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0003_room_room_amenities_roomtype_hostel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomtype",
            name="num_occupancy",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
