# Generated by Django 5.0.6 on 2024-06-01 15:28
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0004_roomtype_num_occupancy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="image",
        ),
    ]
