# Generated by Django 5.0.6 on 2024-07-06 00:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_remove_room_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_mates',
            field=models.ManyToManyField(blank=True, related_name='room_mates', to=settings.AUTH_USER_MODEL),
        ),
    ]
