# Generated by Django 5.0.6 on 2024-07-22 12:43
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0006_room_gender"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="roomamenity",
            options={
                "verbose_name": "Room Amenity",
                "verbose_name_plural": "Room Amenities",
            },
        ),
    ]
