# Generated by Django 5.0.6 on 2024-08-07 16:08
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0007_alter_roomamenity_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="is_locked",
            field=models.BooleanField(default=False),
        ),
    ]
