# Generated by Django 5.0.6 on 2024-11-12 09:44
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0008_room_is_locked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="floor_plan",
            field=models.ImageField(blank=True, null=True, upload_to="floor_plan"),
        ),
    ]
