# Generated by Django 5.0.6 on 2024-10-07 15:53
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0002_alter_chatroom_participants"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="chatroom",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="object_type",
            field=models.CharField(
                choices=[
                    ("hostel", "Hostel"),
                    ("user", "User"),
                    ("room", "Room"),
                    ("public", "Public"),
                ],
                default="public",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="chat",
            name="object_type",
            field=models.CharField(
                choices=[
                    ("hostel", "Hostel"),
                    ("user", "User"),
                    ("room", "Room"),
                    ("public", "Public"),
                ],
                max_length=255,
            ),
        ),
    ]
