# Generated by Django 5.0.6 on 2024-06-25 01:52
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("literals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hostel",
            name="location",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="hostel",
            name="owner_email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="hostel",
            name="owner_name",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="hostel",
            name="owner_phone",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
