# Generated by Django 5.0.6 on 2024-07-07 17:49
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        (
            "literals",
            "0002_hostel_location_hostel_owner_email_hostel_owner_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="hostel",
            name="code",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="hostel",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
