# Generated by Django 5.0.6 on 2024-07-22 12:43
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("literals", "0003_hostel_code_hostel_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="hostel",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="hostels"),
        ),
    ]
