# Generated by Django 5.0.6 on 2024-08-26 14:05
import uuid

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("literals", "0004_hostel_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="HostelPaymentDetail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=1024)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "hostel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="literals.hostel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
