# Generated by Django 5.0.6 on 2024-10-07 17:07
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("literals", "0006_institution"),
    ]

    operations = [
        migrations.AddField(
            model_name="hostel",
            name="dead_line",
            field=models.DateField(null=True),
        ),
    ]
