# Generated by Django 5.0.6 on 2024-11-14 15:39
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("literals", "0007_hostel_dead_line"),
    ]

    operations = [
        migrations.AddField(
            model_name="hostel",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=10
            ),
        ),
    ]
