# Generated by Django 5.0.6 on 2024-05-26 01:15
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("question", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="option",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["created_at"]},
        ),
    ]
