# Generated by Django 5.0.6 on 2024-05-16 22:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('literals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdditionalDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('other_name', models.CharField(blank=True, max_length=200, null=True)),
                ('guardian_full_name', models.CharField(max_length=200)),
                ('ghana_card_number', models.CharField(blank=True, max_length=15, null=True)),
                ('course_of_study', models.CharField(max_length=200)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('admission_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('mobile_number', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('guardian_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('pictur_of_ghana_card', models.ImageField(blank=True, null=True, upload_to='')),
                ('student_id_number', models.CharField(max_length=20)),
                ('date_of_admission', models.DateField()),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='literals.university')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
