# Generated by Django 5.0.6 on 2024-05-18 13:18
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_useradditionaldetail"),
    ]

    operations = [
        migrations.AddField(
            model_name="useradditionaldetail",
            name="responses",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
