# Generated by Django 5.0.6 on 2024-05-26 00:05
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_useradditionaldetail_room_roompayment"),
        ("room", "0003_room_room_amenities_roomtype_hostel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="roompayment",
            name="room_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="room.roomtype",
            ),
        ),
        migrations.AddField(
            model_name="useradditionaldetail",
            name="room_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="room.roomtype",
            ),
        ),
    ]
