# Generated by Django 5.0.6 on 2024-05-28 19:53
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_roompayment_room_type_useradditionaldetail_room_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="roompayment",
            name="first_receipt",
            field=models.ImageField(blank=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="roompayment",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="roompayment",
            name="second_receipt",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
