# Generated by Django 5.0.6 on 2024-05-18 18:59
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_useradditionaldetail_responses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="additional_info",
        ),
    ]
