# Generated by Django 5.0.6 on 2024-05-18 19:43
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_remove_user_additional_info"),
        ("room", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useradditionaldetail",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="room.room",
            ),
        ),
    ]
