# Generated by Django 5.0.6 on 2024-07-07 14:55
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_roompayment_first_receipt_roompayment_is_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="useradditionaldetail",
            name="nickname",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
