# Generated by Django 5.0.6 on 2024-05-19 10:31
import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_useradditionaldetail_room"),
        ("literals", "0003_hostel_semester_year"),
        ("room", "0002_room_hostel_room_image_roompricing"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="hostel",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="literals.hostel",
            ),
        ),
        migrations.CreateModel(
            name="RoomPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount_payed", models.DecimalField(decimal_places=2, max_digits=10)),
                ("note", models.TextField(blank=True)),
                (
                    "room_pricing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="room.roompricing",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
