# Generated by Django 5.0.6 on 2024-09-11 13:14
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_roompayment_hostel"),
        ("literals", "0005_hostelpaymentdetail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="hostel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="literals.hostel",
            ),
        ),
    ]
