# Generated by Django 5.0.6 on 2024-09-11 21:46
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0007_alter_user_hostel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AlterUniqueTogether(
            name="user",
            unique_together=set(),
        ),
    ]
