# Generated by Django 5.0.6 on 2024-05-23 14:49
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0007_alter_user_options_alter_user_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useradditionaldetail",
            name="institution",
        ),
        migrations.RemoveField(
            model_name="useradditionaldetail",
            name="mobile_number",
        ),
        migrations.AlterField(
            model_name="useradditionaldetail",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
