# Generated by Django 5.0.6 on 2024-10-01 09:33
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0008_alter_user_options_alter_user_unique_together"),
        ("literals", "0006_institution"),
    ]

    operations = [
        migrations.AddField(
            model_name="useradditionaldetail",
            name="course_level",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="useradditionaldetail",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="literals.institution",
            ),
        ),
        migrations.AlterField(
            model_name="useradditionaldetail",
            name="course_of_study",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="useradditionaldetail",
            name="date_of_admission",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="useradditionaldetail",
            name="guardian_full_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="useradditionaldetail",
            name="student_id_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
