# Generated by Django 5.0.6 on 2024-10-07 17:29
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0009_useradditionaldetail_course_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="roompayment",
            name="status",
            field=models.CharField(
                choices=[
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                    ("not_verified", "Not Verified"),
                ],
                default="not_verified",
                max_length=20,
            ),
        ),
    ]
